apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitlab-eventsource
  namespace: argo-cicd
spec:
  service:
    ports:
      - name: gitlab-eventsource
        port: 12000
        targetPort: 12000
  webhook:
    snciot-backend2-0:
      port: "12000"
      endpoint: /snciot_backend2-0
      method: POST
      authSecret:
        name: gitlab-webhook-secret
        key: secretToken