apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sample-eventsensor
  namespace: argo-cicd
spec:
  template:
    serviceAccountName: argo
  dependencies:
    - name: webhook-snciot
      eventSourceName: gitlab-eventsource
      eventName: snciot-backend2-0
  triggers:
    - template:
        name: snciot-backend2-0-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: snciot-backend2-0-
                namespace: argo-cicd
              spec:
                serviceAccountName: argo
                entrypoint: snciot-backend2-0-pipeline
                arguments:
                  parameters:
                    - name: branch
                    - name: git-repo-url
                    - name: commit-author
                    - name: commit-message
                    - name: commit-id
                    - name: project-name
                    - name: target-branch
                    - name: build-user
                    - name: git-url
                    - name: git-commit
                    - name: build-time
          parameters:
            - src:
                dependencyName: webhook-snciot
                dataKey: ref
              dest: spec.arguments.parameters.0.value
              transform:
                expression: "trimPrefix(\"refs/heads/\", value)"
            - src:
                dependencyName: webhook-snciot
                dataKey: repository.git_http_url
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: webhook-snciot
                dataKey: commits[0].author.name
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: webhook-snciot
                dataKey: commits[0].message
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: webhook-snciot
                dataKey: after
              dest: spec.arguments.parameters.4.value
            - src:
                dependencyName: webhook-snciot
                dataKey: project.name
              dest: spec.arguments.parameters.5.value
            - src:
                dependencyName: webhook-snciot
                dataKey: ref
              dest: spec.arguments.parameters.6.value
              transform:
                expression: "trimPrefix(\"refs/heads/\", value)"
            - src:
                dependencyName: webhook-snciot
                dataKey: user_username
              dest: spec.arguments.parameters.7.value
            - src:
                dependencyName: webhook-snciot
                dataKey: repository.git_http_url
              dest: spec.arguments.parameters.8.value
            - src:
                dependencyName: webhook-snciot
                dataKey: after
              dest: spec.arguments.parameters.9.value
            - src:
                dependencyName: webhook-snciot
                dataKey: commits[0].timestamp
              dest: spec.arguments.parameters.10.value
      policy:
        status:
          allow: [200, 201]