apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sample-eventsensor
  namespace: argo-cicd
spec:
  template:
    serviceAccountName: argo
  dependencies:
    - name: snciot-backend2-0-dep
      eventSourceName: gitlab-eventsource
      eventName: snciot-backend2-0
      condition:
        expression: |
          trimPrefix("refs/heads/", body.ref) in ["master", "50"]
  triggers:
    - template:
        name: snciot-backend2-0-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: snciot-backend2-0-
                namespace: argo-cicd
              spec:
                serviceAccountName: argo
                entrypoint: snciot-backend2-0-sensor-pipeline
                templates:
                  - name: snciot-backend2-0-sensor-pipeline
                    steps:
                      - - name: snciot-backend2-0-pull
                          templateRef:
                            name: snciot-backend2-0-pull-template
                            template: snciot-backend2-0-pull
                          arguments:
                            parameters:
                              - name: branch
                                value: "{{workflow.parameters.branch}}"
                              - name: url
                                value: "{{workflow.parameters.git-repo-url}}"

                      - - name: snciot-backend2-0-build
                          templateRef:
                            name: snciot-backend2-0-build-template
                            template: snciot-backend2-0-build
                          arguments:
                            parameters:
                              - name: branch
                                value: "{{workflow.parameters.branch}}"

                      - - name: snciot-backend2-0-deploy
                          templateRef:
                            name: snciot-backend2-0-deploy-template
                            template: snciot-backend2-0-deploy
                          arguments:
                            parameters:
                              - name: target-branch
                                value: "{{workflow.parameters.target-branch}}"
                              - name: project-name
                                value: "{{workflow.parameters.project-name}}"
                              - name: git-commit
                                value: "{{workflow.parameters.git-commit}}"
                              - name: commit-message
                                value: "{{workflow.parameters.commit-message}}"
                              - name: build-time
                                value: "{{workflow.parameters.build-time}}"
                              - name: git-url
                                value: "{{workflow.parameters.git-repo-url}}"
                  - name: snciot-backend2-0-dingtalk-notify
                    templateRef:
                      name: snciot-backend2-0-dingtalk-notify-template
                      template: snciot-backend2-0-dingtalk-notify
                arguments:
                  parameters:
                    - name: branch
                      value: "master"
                    - name: git-repo-url
                      value: ""
                    - name: commit-author
                      value: "Unknown Author"
                    - name: commit-message
                      value: "No commit message"
                    - name: commit-id
                      value: "No commit ID"
                    - name: project-name
                      value: "Unknown Project"
                    - name: target-branch
                      value: "master"
                    - name: build-user
                      value: "Unknown User"
                    - name: git-url
                      value: ""
                    - name: git-commit
                      value: "No commit ID"
                    - name: build-time
                      value: "Unknown Timestamp"
                    - name: workflow-namespace
                      value: "argo-cicd"
                    - name: workflow-name
                      value: "snciot-backend2-0-workflow"
                    - name: workflow-status
                      value: "Unknown"
                    - name: workflow-duration
                      value: "0s"
                    - name: workflow-start-time
                      value: "Unknown"
                onExit: snciot-backend2-0-dingtalk-notify
          parameters:
            - src:
                dependencyName: snciot-backend2-0-dep
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: snciot-backend2-0-dep
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: snciot-backend2-0-dep
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: snciot-backend2-0-dep
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: snciot-backend2-0-dep
              dest: spec.arguments.parameters.4.value
            - src:
                dependencyName: snciot-backend2-0-dep
              dest: spec.arguments.parameters.5.value
            - src:
                dependencyName: snciot-backend2-0-dep
              dest: spec.arguments.parameters.6.value
            - src:
                dependencyName: snciot-backend2-0-dep
              dest: spec.arguments.parameters.7.value
            - src:
                dependencyName: snciot-backend2-0-dep
              dest: spec.arguments.parameters.8.value
            - src:
                dependencyName: snciot-backend2-0-dep
              dest: spec.arguments.parameters.9.value
            - src:
                dependencyName: snciot-backend2-0-dep
              dest: spec.arguments.parameters.10.value
      policy:
        status:
          allow: [200, 201]