apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sample-eventsensor
spec:
  dependencies:
    - name: snciot-backend2-0-dep
      eventSourceName: gitlab-eventsource
      eventName: snciot-backend2-0
  triggers:
    - template:
        name: snciot-backend2-0-trigger
        k8s:
          group: batch
          kind: Job
          metadata:
            name: snciot-backend2-0-job
          spec:
            template:
              spec:
                containers:
                  - name: snciot-backend2-0-container
                    image: busybox
                    command: ["echo", "Triggered"]
                restartPolicy: OnFailure
  transform:
    - name: decode-gitlab-payload
      transformer:
        jq: |
          .body = .data  # 将原始 Webhook 数据放入 body 中
          .commits = if .body.commits != null and length(.body.commits) > 0 then .body.commits[0] else {} end  # 获取 commits 数组中的第一个元素
          .body  # 返回修改后的 body 数据

    - name: print-webhook-event
      transformer:
        jq: |
          # 输出 Webhook 事件的全部内容，帮助调试
          .body = .data
          .body  # 打印原始事件数据，用于调试和验证字段结构
