apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: snciot-backend2-0-eventbinding
  namespace: argo-cicd
spec:
  event:
    selector: "body.ref != nil"
  submit:
    workflowTemplateRef:
      name: snciot-backend2-0-pipeline
    arguments:
      parameters:
        - name: branch
          valueFrom:
            event: body.ref
            expression: 'trimPrefix("refs/heads/", value)'
        - name: git-repo-url
          valueFrom:
            event: body.repository.git_http_url
        - name: commit-message
          valueFrom:
            event: body.commits[0].message
        - name: commit-id
          valueFrom:
            event: body.commits[0].id
        - name: project-name
          valueFrom:
            event: body.project.name
        - name: target-branch
          valueFrom:
            event: body.ref
            expression: 'trimPrefix("refs/heads/", value)'
        - name: build-user
          valueFrom:
            event: body.user_username
        - name: git-url
          valueFrom:
            event: body.repository.git_http_url
        - name: git-commit
          valueFrom:
            event: body.commits[0].id
        - name: build-time
          valueFrom:
            event: body.commits[0].timestamp
        # 添加缺失的参数
        - name: commit-author
          valueFrom:
            event: body.commits[0].author.name