apiVersion: v1
kind: Secret
metadata:
  name: gitlab-access
  namespace: argo-cicd
type: Opaque
data:
  # 需要具有api权限的个人访问令牌
  # 示例: echo -n '完整令牌-*****-********' | base64
  token: ？？？？？？？？？？？？？？？？？？？？？？？？？？
