apiVersion: v1
kind: Secret
metadata:
  name: gitlab-pull-secret
  namespace: argo-cicd
type: Opaque
data:
  # GitLab username (base64编码)
  # 示例: echo -n 'your_gitlab_username' | base64
  username: cm9vdA==
  
  # GitLab password (base64编码)
  # 示例: echo -n 'your_gitlab_password' | base64
  password: THcxOTk0MTAwNzEzLi4=