apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc-2
  namespace: argo-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client