apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stan-pv-0
  namespace: argo-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
